server:
  # 端口
  port: 8888
spring:
  application:
    name: seckill
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  # thymeleaf 渲染
  thymeleaf:
#    enabled: true
    cache: false
#    servlet:
#      content-type: text/html
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
  # 静态资源处理
  web:
    resources:
      chain:
        cache: true
        enabled: true
        compressed: true
      # 启动默认静态资源处理，默认启动
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600
      static-locations: classpath:/static/
  # Redis 配置信息
  data:
    redis:
      host:
      port:
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    # JSON处理时忽略非空字段
    default-property-inclusion: non_null
  rabbitmq:
#    服务器
    host:
    username:
    password:
    virtual-host:
    port:
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
      template:
        retry:
          #发布重试，默认false
          enabled: true
          #重试时间，默认1000ms
          initial-interval: 1000ms
          #重试最大次数，默认3次
          max-attempts: 3
          #最大重试间隔时间
          max-interval: 10000ms
          #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
          multiplier: 1.0
logging:
  level:
    top.yolopluto.seckill: debug
mybatis:
  # 配置mybatis的配置文件和mapper文件
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
